### PR TITLE
added setSkin(Skin) method

### PR DESCRIPTION
**Pull request by kaerns**
To WolverinDev:
Ich lass das mal so im Raum stehen, hab zufällig die Disskusion im Spigot-forum verfolgt und das hier schnell gebastelt. Ist ungetestet also sollte nochmal getestet werden, denn ich teste es nicht. Vom Code ansich sollte es Funktionieren.
Wenn es niemand Testen will hab ich auch kein problem damit wenn die Pullrequest abgelehnt wird.

To everyone else:
If you wish to test this, go for it and report back if it works or not.

### CODE REVIEW

**Comment by WolverinDEV** [comment]
Should work.
I will test it later but this is a good idea :D

**Comment by kaerns** [comment]
would recommend to check the whole skin api because it looked to me that its only half finished

**Comment by WolverinDEV** [comment]
Realy?
I dont realy know what you mean. You're confusing me

**Comment by kaerns** [comment]
nvm just checked some uses for the GameProfile class. i thought Skin#apply(GameProfile) was useless ^^

**Comment by WolverinDEV** [comment]
Well not all methods are used :) Some emthods are just for API purposes :D

**Comment by SeniorCluckers** [comment]
I finally got skin changing working. Yay :D! 

@WolverinDEV @essem2 

You think its possible using your API to create custom skins. For instance using a link to set a custom player skin of the players choosing. 

Example:

/skin <link to skin here>

Sets your skin to the link specified.

What would you say?

**Comment by kaerns** [comment]
@SeniorCluckers 
its possible but not worth it. To realize it you need to upload the skin to a minecraft-account and then pull it via the api because the skin need a signed mojang texture-server link. If you really wan't it to do you can take a look at wiki.vg . I can't recommend using this because its even really hard for me (never tried it).

**Comment by SeniorCluckers** [comment]
@essem2 

You know I seen this https://www.spigotmc.org/resources/customskins.25417/.  https://github.com/InventivetalentDev/CustomSkins/blob/master/src/main/java/org/inventivetalent/customskins/CustomSkins.java

What do you think about that?

**Comment by kaerns** [comment]
@SeniorCluckers 
What should i think about it? Its an experienced developer and it uses exact the method i mentioned but it uses it as a web-app. You could use the api to outsource the part with uploading the skin but if this service is down you can nothing do about it.

**Comment by SeniorCluckers** [comment]
@essem2  No no I know that. Wait once a skin is uploaded to an account its possible to save the skin in the server files. Correct? Therefore we are able to use it in the future/present as a skin.

**Comment by kaerns** [comment]
@SeniorCluckers 
yup it is.  you need to save the "texture" and "signature" of a skin.
an example for texture is this: `eyJ0aW1lc3RhbXAiOjE0NTMwNDg4MTIyODYsInByb2ZpbGVJZCI6Ijk5MDVkZDg1NTgxNjRlNmM5Y2VkYTk4NWM3ZDliMGRlIiwicHJvZmlsZU5hbWUiOiJEZXZQaXhlbCIsInNpZ25hdHVyZVJlcXVpcmVkI			jp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjZjZTk2OGZkYzY3YzlkMDU2M2JmMmVjZmEzM2UwYjQ4ODI4MWQ2OGE5ODZhNWU2M2JiYWZkZDhlOWMwZmZiYyJ9LCJDQVBFIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTc4OTMyNzBmN2RmNjdhMjBlYTljOGFiNTJkN2FmZjIzMjcwZmM0M2ExMWZiM2RhZTYyMjkxNjM0YWY0MjQifX19`

Edit: We should use a private chat if this conversation is going longer because this is a pullrequest for the setSkin method and not a discussion about how to do things ^^

**Comment by SeniorCluckers** [comment]
@essem2 

Yeah you're probably right. Apologies @WolverinDEV .

**Pull request merged**
